
```{R}
library(Biobase)
library(knitr)
library(reshape2)
library(ggplot2)
# library(HSMMSingleCell)
library(monocle)
library(RColorBrewer)
library(Seurat)
library(colorRamps)
library(pheatmap)
library(stringr)
library(GSVA)
library(ComplexHeatmap)
library(dendsort)
getPalette = colorRampPalette(brewer.pal(9, "Set1"))#Paired
my_comparison=function(p=compare_result){
  a=p[p$p<0.05,]
  result=list()
  length(result)=nrow(a)
  for(i in 1:nrow(a)){
    result[[i]]=c(a$group1[i],a$group2[i])
  }
  return(result)
  
}
convertMouseGeneList <- function(x){
  require("biomaRt")
  human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
  genesV2 = getLDS(attributes = c("hgnc_symbol"),
                   filters = "hgnc_symbol",
                   values = x , martL = mouse,
                   attributesL = c("mgi_symbol"),
                   mart = human, uniqueRows=T)
  
  return(genesV2)
   
}
g2m.genes=convertMouseGeneList(cc.genes.updated.2019$g2m.genes)
s.genes=convertMouseGeneList(cc.genes.updated.2019$s.genes)
getPalette = colorRampPalette(brewer.pal(9, "Set1"))#Paired
```

```{r}

gzfile=list.files(path = 'E:/WCH/NDT/withercc',pattern = '.tsv.gz')

countdata=list()
for(i in gzfile){
  print(i)
  countdata[[gsub('.count.*','',i)]]=read.table(paste0('E:/WCH/NDT/withercc/',i),header = T)
  
}

names(countdata)=sapply(names(countdata),function(x){if(grepl("^23",x)){return(substr(x,3,nchar(x)))}else{return(x)}})

barcode=read.table('E:/singlecell/all_count/Barcode.txt',header = F)
allbarcode=paste0(rep(c("AA","TT","CC","GG"),each=96),barcode$V2)

for(i in names(countdata)){
  countdata[[i]]=countdata[[i]][,c('gene',intersect(allbarcode,colnames(countdata[[i]])))]
  
}

for(i in names(countdata)){
  colnames(countdata[[i]])=c('gene',paste(i,colnames(countdata[[i]])[-1],sep = '_'))
  
  
}
lapply(countdata,dim)

data=countdata[[1]]
for(i in 2:length(gzfile)){
  
  data=merge(data,countdata[[i]],by='gene',all=T)
  
}

rownames(data)=data$gene
data=data[,-1]
data[is.na(data)]=0
data=as(as.matrix(data),'sparseMatrix')
```

```{r}
dataname0="20210227withercc"
seuratData <- CreateSeuratObject(data) 
seuratData@meta.data$sample=seuratData@meta.data$orig.ident
seuratData@meta.data$NDT=sapply(colnames(seuratData),function(x){substr(x,1,1)})

seuratData@meta.data$batcheffect=sapply(seuratData@meta.data$sample,function(x){if(x%in%c("D61","D62","T42","T43")){return("20191030DT")}else{return("20190928_15G_merge")}})

seuratData[["percent.mt"]] = colSums(as.matrix(seuratData@assays$RNA@counts[grep('^mt-',rownames(seuratData@assays$RNA@counts)),]))/seuratData$nCount_RNA
seuratData[["percent.ercc"]] = colSums(as.matrix(seuratData@assays$RNA@counts[grep('^ERCC-',rownames(seuratData@assays$RNA@counts)),]))/seuratData$nCount_RNA
p1=VlnPlot(seuratData, c("nCount_RNA", "nFeature_RNA"), pt.size = 0.1, ncol = 2, group.by = "NDT")
p2=VlnPlot(seuratData, c("nCount_RNA", "nFeature_RNA"), pt.size = 0.1, ncol = 2, group.by = "sample")
p3=VlnPlot(seuratData, c('percent.mt','percent.ercc'), pt.size = 0.1, ncol = 2, group.by = "NDT")
p4=VlnPlot(seuratData, c('percent.mt','percent.ercc'), pt.size = 0.1, ncol = 2, group.by = "sample")

seuratData <- subset(seuratData, subset = nFeature_RNA > 200&nFeature_RNA < 6000 & percent.mt < 0.05 & percent.ercc<0.1)
p5=VlnPlot(seuratData, c("nCount_RNA", "nFeature_RNA"), pt.size = 0.1, ncol = 2, group.by = "NDT")
p6=VlnPlot(seuratData, c("nCount_RNA", "nFeature_RNA"), pt.size = 0.1, ncol = 2, group.by = "sample")
p7=VlnPlot(seuratData, c('percent.mt','percent.ercc'), pt.size = 0.1, ncol = 2, group.by = "NDT")
p8=VlnPlot(seuratData, c('percent.mt','percent.ercc'), pt.size = 0.1, ncol = 2, group.by = "sample")
pdf(paste0(dataname0,"gene_count.pdf"))
print(p1)
print(p2)
print(p3)
print(p4)
print(p5)
print(p6)
print(p7)
print(p8)
dev.off()

seuratData=seuratData[grep("ERCC-",rownames(seuratData),invert = T),]

seuratData=NormalizeData(object = seuratData, normalization.method = "LogNormalize", scale.factor = 10000)
seuratData <- CellCycleScoring(seuratData, s.features = s.genes$MGI.symbol, g2m.features =g2m.genes$MGI.symbol)#, set.ident = TRUE)

# seuratData@assays$RNA@data=log(as.matrix(seuratData@assays$RNA@data)+1)
# seuratData@assays$RNA@data=as(seuratData@assays$RNA@data,"sparseMatrix")
#https://satijalab.org/seurat/v3.1/cell_cycle_vignette.html 设置cell cycle的校正 seurat使用的是score,science paper中使用phase
seuratData <- FindVariableFeatures(seuratData, selection.method = "vst", x.cutoff=c(0.01,Inf),y.cutoff=0.01,nfeatures = 5000)
seuratData <- ScaleData(object = seuratData, vars.to.regress = c("S.Score", "G2M.Score",'percent.mt','percent.ercc','nFeature_RNA',"batcheffect"))

#Dimension reduction
seuratData <- RunPCA(seuratData, npcs = 70, verbose = FALSE,features =VariableFeatures(seuratData) )
# ElbowPlot(seuratData, ndims = 70)


# seuratData=JackStraw(seuratData, num.replicate = 100,dims = 100)
# seuratData <- ScoreJackStraw(seuratData, dims = 1:70)
# JackStrawPlot(seuratData, dims = 1:50)

# dims=which(seuratData@reductions$pca@jackstraw$overall.p.values[,2]>0.05)[1]-1
dims=20
seuratData <- RunTSNE(seuratData, dims = 1:dims, verbose = FALSE,check_duplicates = FALSE)
seuratData <- FindNeighbors(seuratData,reduction = 'pca', verbose = FALSE, dims = 1:dims)
seuratData <- FindClusters(seuratData, algorithm = 1, random.seed = 256, resolution = 1)
pdf(paste0(dataname0,"cluster.pdf"))
DimPlot(seuratData,  reduction = "tsne", group.by = "seurat_clusters", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$seurat_clusters))))
DimPlot(seuratData,  reduction = "tsne", group.by = "sample", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$month))))
DimPlot(seuratData,  reduction = "tsne", group.by = "NDT", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$month_version))))
dev.off()

genes_to_check = c("B2m",'Esr1','Pgr','Bcl11b','Tspan8','Tspan18','Tspan1','Procr','Axin2','Krt8','Krt18','Krt19','Krt5','Krt14','Krt17','Lgr5','Dll1','Elf5','Cd14','Cd200','Cd34','Aldh1a1','Sox9','Mycn','Tbx2','Sema3a','Mki67','Top2a','Ccnd1','Ccnd2','Ccnd3','Hes1','Gli1','Gli2','Gli3','Hey1','Spp1','Cd47','Slc6a2','Bcl11b','Pecam1','Ptprc','Col1a1','Itgb3','Itga2','Ly6a','Trpm3','Brca1','Lepr','Ptger3','Tmem97','Cd14','Prom1',"Erbb2","Esr1","Epcam","Cd274","Ar","Cdh1","Cd3e","Cd68","Cd8a","Cd4",'Krt14','Krt5',"Dpp4","Dlk1","Tgfb1","Tgfb2","Ifng","Ctla4","S100a4","Tnf","Itgam","Itgax","Pecam1","Acta2","Lyve1","Cd19","Cd78","FoxP3","Cdh5","Ly6g","Ly6c",'Klrk1', 'Pdpn','Siglecf', 'Cd24',"Cd24a", 'Fcgr1a',"Cd64a","Cd64b","Cd64c","H2-Q1",  "H2-Q2",  "H2-Q4" , "H2-Q6" , "H2-Q7" , "H2-Q10",'Cd200','Krt14','Krt8','Epcam','Acta2','Pdpn','Emb','Cd200r1','Cd200r2','Cd200r4',"Cd79a")

length(genes_to_check)
genes_to_check<-sort(intersect(rownames(seuratData@assays$RNA@counts),genes_to_check))
length(genes_to_check)
genes_to_check

jpeg(paste0(dataname0,"_fea.jpg"),width = 2000,height = 1600)
b=FeaturePlot(object = seuratData,genes_to_check,reduction = "tsne",pt.size = 0.3, ncol = 10)+NoLegend()
print(b)
dev.off()

pdf(paste0(dataname0,"_fea.pdf"),width = 40,height = 50)
b=FeaturePlot(object = seuratData,genes_to_check,reduction = "tsne",pt.size = 0.8, ncol = 10)+NoLegend()
print(b)
dev.off()

seuratData@meta.data$celltype=plyr::mapvalues(seuratData@meta.data$seurat_clusters,
                                              from = c(c(1,6),c(3,0,2,7,11),5,13,c(4,9,10,8,12)),
                                              to=c(rep("basal",2),c("Elf5",rep("Esr1",3),"lum"),
                                                   "macrophage","endo",rep("fib",5))
                                                )
seuratData@meta.data$celltypeNDT=paste0(seuratData@meta.data$NDT,"_",seuratData@meta.data$celltype)
seuratData@meta.data$celltype=factor(seuratData@meta.data$celltype,levels = c("Elf5","Esr1","lum","basal","fib","endo","macrophage"))
seuratData@meta.data$celltypeNDT=factor(seuratData@meta.data$celltypeNDT,levels = paste0(rep(c("N","D","T"),each=7),"_",c("Elf5","Esr1","lum","basal","fib","endo","macrophage")))

pdf(paste0(dataname0,"cluster.pdf"))
DimPlot(seuratData,  reduction = "tsne", group.by = "seurat_clusters", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$seurat_clusters))))
DimPlot(seuratData,  reduction = "tsne", group.by = "sample", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$month))))
DimPlot(seuratData,  reduction = "tsne", group.by = "NDT", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$month_version))))
DimPlot(seuratData,  reduction = "tsne", group.by = "celltype", label = TRUE)+scale_fill_manual(values = getPalette(length(unique(seuratData@meta.data$month_version))))
dev.off()


save(seuratData,file = paste0(dataname0,"WCH.RData"))
```
